language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - "pip install ."
  - "pip install nose"
# command to run tests, e.g. python setup.py test
script: nosetests
